# Generated by Django 3.2 on 2022-06-13 07:45

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_for', multiselectfield.db.fields.MultiSelectField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Couples', 'Couples'), ('Unisex', 'Unisex'), ('Family', 'Family'), ('Student', 'Student'), ('All', 'All')], max_length=45)),
                ('title', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=100)),
                ('floor', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('location', models.CharField(help_text='(Please enter latitude and longitude of this property/location). Example: 28.4930741,77.0946958', max_length=800, null=True)),
                ('price', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('area_sqft_size', models.IntegerField()),
                ('property_age', models.CharField(max_length=20)),
                ('kitchen', models.CharField(blank=True, choices=[('Not Available', 'Not Available'), ('Normal Kitchen', 'Normal Kitchen'), ('Modular Kitchen', 'Modular Kitchen')], default='Modular Kitchen', max_length=100)),
                ('parking', models.CharField(choices=[('Free Parking', 'Free Parking'), ('Paid Parking', 'Paid Parking')], default='Free Parking', max_length=50)),
                ('furnished_type', models.CharField(choices=[('Unfurnished', 'Unfurnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Fully-Furnished', 'Fully-Furnished')], default='Unfurnished', max_length=50)),
                ('security_amount', models.CharField(max_length=100)),
                ('sharing', models.CharField(choices=[('Allowed', 'Allowed'), ('Not Allowed', 'Not Allowed')], default='Allowed', max_length=50)),
                ('internet', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=50)),
                ('ameneties', multiselectfield.db.fields.MultiSelectField(choices=[('Air Conditioning', 'AirConditioning'), ('Swimming Pool', 'SwimmingPool'), ('Elevator', 'Elevator'), ('Laundry Room', 'LaundryRoom'), ('Window Covering', 'WindowCovering'), ('Pets Allowed', 'PetsAllowed'), ('Free WIFI', 'FreeWIFI'), ('Gyser', 'Gyser'), ('Refrigerator', 'Refrigerator'), ('TV', 'TV'), ('GYM', 'GYM'), ('Car Parking', 'CarParking'), ('Alarm', 'Alarm'), ('Power backup', 'Powerbackup'), ('Park', 'Park'), ('RO Water', 'ROWater'), ('CCTV Camera', 'CCTVCamera')], max_length=174)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=100)),
                ('owner_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')])),
                ('owner_secondary_phone', models.CharField(blank=True, help_text='(Optional)', max_length=10, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')])),
                ('owner_photo', imagekit.models.fields.ProcessedImageField(upload_to='images/property_images/%Y/%m/%d/')),
                ('photo_main', imagekit.models.fields.ProcessedImageField(upload_to='images/property_images/%Y/%m/%d/')),
                ('front_home_photo', imagekit.models.fields.ProcessedImageField(upload_to='images/property_images/%Y/%m/%d/')),
                ('first_room_photo', imagekit.models.fields.ProcessedImageField(upload_to='images/property_images/%Y/%m/%d/')),
                ('second_room_photo', imagekit.models.fields.ProcessedImageField(blank=True, help_text='(Optional)', upload_to='images/property_images/%Y/%m/%d/')),
                ('third_room_photo', imagekit.models.fields.ProcessedImageField(blank=True, help_text='(Optional)', upload_to='images/property_images/%Y/%m/%d/')),
                ('kitchen_photo', imagekit.models.fields.ProcessedImageField(blank=True, help_text='(Optional)', upload_to='images/property_images/%Y/%m/%d/')),
                ('bathroom_photo', imagekit.models.fields.ProcessedImageField(upload_to='images/property_images/%Y/%m/%d/')),
                ('property_video', models.FileField(blank=True, default=None, help_text='(Optional)', upload_to='videos/property_videos/%Y/%m/%d/')),
                ('views', models.IntegerField(default=0, editable=False)),
                ('no_of_days_advance', models.IntegerField(default=0, editable=False)),
                ('start_date', models.DateField(blank=True, editable=False, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_it_featured_property', models.BooleanField(default=False)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('favourites', models.ManyToManyField(blank=True, default=None, editable=False, related_name='favorite', to=settings.AUTH_USER_MODEL)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyGallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(max_length=200, upload_to='images/property_images/%Y/%m/%d/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            options={
                'verbose_name': 'propertygallary',
                'verbose_name_plural': 'Property Gallery',
            },
        ),
    ]
