# Generated by Django 3.2 on 2022-06-03 07:00

import ckeditor.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_story', ckeditor.fields.RichTextField(blank=True)),
                ('our_mission', ckeditor.fields.RichTextField(blank=True)),
                ('security', ckeditor.fields.RichTextField(blank=True)),
                ('manage', ckeditor.fields.RichTextField(blank=True)),
                ('promise', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'aboutus',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_banner', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='site/banners/main_banner/%Y/%m/%d/')),
                ('app_banner', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='site/banners/app_banner/%Y/%m/%d/')),
                ('our_story', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='site/banners/our_story/%Y/%m/%d/')),
                ('our_mission', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='site/banners/our_mission/%Y/%m/%d/')),
                ('alt_text', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resent_properties', ckeditor.fields.RichTextField(blank=True)),
                ('how_works_property', ckeditor.fields.RichTextField(blank=True)),
                ('how_works_agent', ckeditor.fields.RichTextField(blank=True)),
                ('how_works_deal', ckeditor.fields.RichTextField(blank=True)),
                ('featured_properties', ckeditor.fields.RichTextField(blank=True)),
                ('explore_agents', ckeditor.fields.RichTextField(blank=True)),
                ('find_by_location', ckeditor.fields.RichTextField(blank=True)),
                ('apps', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'homepage',
                'verbose_name_plural': 'homepage',
            },
        ),
        migrations.CreateModel(
            name='membership_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_plans', ckeditor.fields.RichTextField(blank=True)),
                ('tenant_plans', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'membership_page',
                'verbose_name_plural': 'membership_page',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('details', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'service',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('profile_img', imagekit.models.fields.ProcessedImageField(upload_to='images/about_images/team_members/%Y/%m/%d/')),
            ],
        ),
    ]
